# config.yaml
model:
  name: "Seokhwa"
  version: "1.0"

training:
  batch_size: 32
  epochs: 10

data:
  
  train_path: "data/train"
  val_path: "data/val"
  audio_path: 'audio/'

optimizer:
  type: "adam"
  learning_rate: 0.001

training:
  epochs: 10
callbacks:
  early_stopping:
    monitor: "val_loss"
    patience: 3
  model_checkpoint:
    filepath: "models/best_model"
    save_best_only: true

hardware:
  use_gpu: true
  gpu_memory_fraction: 0.8



